// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kszpkzlkevjsqncfwhvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzenBremxrZXZqc3FuY2Z3aHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjAxNzQsImV4cCI6MjA2NTM5NjE3NH0.ZGmqKFYXGdsyk6oekGc2OhTeiUKtZlrFowRlqaXoiA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);